<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3VxOINw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3VxOINw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3VxOINw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3VxOINw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3VxOINw\App_KernelDevDebugContainer([
    'container.build_hash' => '3VxOINw',
    'container.build_id' => '79083248',
    'container.build_time' => 1621020936,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3VxOINw');
